/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: message.proto */

#ifndef PROTOBUF_C_message_2eproto__INCLUDED
#define PROTOBUF_C_message_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _YourPackageName__PayloadMessage YourPackageName__PayloadMessage;


/* --- enums --- */

typedef enum _YourPackageName__PayloadMessage__MessageType {
  YOUR_PACKAGE_NAME__PAYLOAD_MESSAGE__MESSAGE_TYPE__TYPE_UNKNOWN = 0,
  YOUR_PACKAGE_NAME__PAYLOAD_MESSAGE__MESSAGE_TYPE__TYPE_CAPITAL = 1,
  YOUR_PACKAGE_NAME__PAYLOAD_MESSAGE__MESSAGE_TYPE__TYPE_SMALL = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(YOUR_PACKAGE_NAME__PAYLOAD_MESSAGE__MESSAGE_TYPE)
} YourPackageName__PayloadMessage__MessageType;

/* --- messages --- */

struct  _YourPackageName__PayloadMessage
{
  ProtobufCMessage base;
  char *payload;
  YourPackageName__PayloadMessage__MessageType type;
};
#define YOUR_PACKAGE_NAME__PAYLOAD_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&your_package_name__payload_message__descriptor) \
    , (char *)protobuf_c_empty_string, YOUR_PACKAGE_NAME__PAYLOAD_MESSAGE__MESSAGE_TYPE__TYPE_UNKNOWN }


/* YourPackageName__PayloadMessage methods */
void   your_package_name__payload_message__init
                     (YourPackageName__PayloadMessage         *message);
size_t your_package_name__payload_message__get_packed_size
                     (const YourPackageName__PayloadMessage   *message);
size_t your_package_name__payload_message__pack
                     (const YourPackageName__PayloadMessage   *message,
                      uint8_t             *out);
size_t your_package_name__payload_message__pack_to_buffer
                     (const YourPackageName__PayloadMessage   *message,
                      ProtobufCBuffer     *buffer);
YourPackageName__PayloadMessage *
       your_package_name__payload_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   your_package_name__payload_message__free_unpacked
                     (YourPackageName__PayloadMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*YourPackageName__PayloadMessage_Closure)
                 (const YourPackageName__PayloadMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor your_package_name__payload_message__descriptor;
extern const ProtobufCEnumDescriptor    your_package_name__payload_message__message_type__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_message_2eproto__INCLUDED */
