/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: message.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "message.pb-c.h"
void   your_package_name__payload_message__init
                     (YourPackageName__PayloadMessage         *message)
{
  static const YourPackageName__PayloadMessage init_value = YOUR_PACKAGE_NAME__PAYLOAD_MESSAGE__INIT;
  *message = init_value;
}
size_t your_package_name__payload_message__get_packed_size
                     (const YourPackageName__PayloadMessage *message)
{
  assert(message->base.descriptor == &your_package_name__payload_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t your_package_name__payload_message__pack
                     (const YourPackageName__PayloadMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &your_package_name__payload_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t your_package_name__payload_message__pack_to_buffer
                     (const YourPackageName__PayloadMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &your_package_name__payload_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
YourPackageName__PayloadMessage *
       your_package_name__payload_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (YourPackageName__PayloadMessage *)
     protobuf_c_message_unpack (&your_package_name__payload_message__descriptor,
                                allocator, len, data);
}
void   your_package_name__payload_message__free_unpacked
                     (YourPackageName__PayloadMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &your_package_name__payload_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue your_package_name__payload_message__message_type__enum_values_by_number[3] =
{
  { "TYPE_UNKNOWN", "YOUR_PACKAGE_NAME__PAYLOAD_MESSAGE__MESSAGE_TYPE__TYPE_UNKNOWN", 0 },
  { "TYPE_CAPITAL", "YOUR_PACKAGE_NAME__PAYLOAD_MESSAGE__MESSAGE_TYPE__TYPE_CAPITAL", 1 },
  { "TYPE_SMALL", "YOUR_PACKAGE_NAME__PAYLOAD_MESSAGE__MESSAGE_TYPE__TYPE_SMALL", 2 },
};
static const ProtobufCIntRange your_package_name__payload_message__message_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex your_package_name__payload_message__message_type__enum_values_by_name[3] =
{
  { "TYPE_CAPITAL", 1 },
  { "TYPE_SMALL", 2 },
  { "TYPE_UNKNOWN", 0 },
};
const ProtobufCEnumDescriptor your_package_name__payload_message__message_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "your_package_name.PayloadMessage.MessageType",
  "MessageType",
  "YourPackageName__PayloadMessage__MessageType",
  "your_package_name",
  3,
  your_package_name__payload_message__message_type__enum_values_by_number,
  3,
  your_package_name__payload_message__message_type__enum_values_by_name,
  1,
  your_package_name__payload_message__message_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor your_package_name__payload_message__field_descriptors[2] =
{
  {
    "payload",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(YourPackageName__PayloadMessage, payload),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(YourPackageName__PayloadMessage, type),
    &your_package_name__payload_message__message_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned your_package_name__payload_message__field_indices_by_name[] = {
  0,   /* field[0] = payload */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange your_package_name__payload_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor your_package_name__payload_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "your_package_name.PayloadMessage",
  "PayloadMessage",
  "YourPackageName__PayloadMessage",
  "your_package_name",
  sizeof(YourPackageName__PayloadMessage),
  2,
  your_package_name__payload_message__field_descriptors,
  your_package_name__payload_message__field_indices_by_name,
  1,  your_package_name__payload_message__number_ranges,
  (ProtobufCMessageInit) your_package_name__payload_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
